backend:
  name: git-gateway
  repo: roryaherne/tirol-dragon
  local_backend: true

media_folder: static/assets
public_folder: /assets

collections:
  - name: schedule
    label: Schedule
    folder: /content/schedule
    create: true
    fields:
      - { label: Title, name: title, hint: "unique title eg: Monday Bjj 1" }
      - { label: day, name: day, widget: select, options: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]}
      - { label: "Start Time", name: startTime, widget: string}
      - { label: "End Time", name: endTime, widget: string}
      - { label: "Class Name", name: classLabel, widget: string}
  - name: coaches
    label: Coaches
    folder: /content/coaches
    create: true
    fields:
      - { label: Title, name: title, hint: "unique title eg: Victor Duarte" }
      - { label: about, name: about, widget: text}
      - { label: image, name: image, widget: image }
  - name: faqs
    label: FAQs
    folder: /content/faqs
    create: true
    fields:
      - { label: Question, name: title, widget: string }
      - { label: Answer, name: answer, widget: text }
  - name: features
    label: Features
    folder: /content/features
    create: true
    fields:
      - { label: Title, name: title }
      - { label: Name, name: name }
      - { label: Body, name: body, widget: text }
      - { label: Image, name: image, widget: image }